// src/routes/teacher.js
const express = require('express')
const router  = express.Router()
const ctrl    = require('../controllers/teacherController')
const tgCtrl  = require('../controllers/telegramController')
const auth    = require('../middleware/auth')
const roles   = require('../middleware/roles')

router.use(auth, roles('teacher'))

router.get('/dashboard',                         ctrl.getDashboard)
router.get('/subscription',                      ctrl.getSubscriptionInfo)
router.post('/classes',                          ctrl.createClass)
router.get('/classes',                           ctrl.getMyClasses)
router.put('/classes/:classId/amount',           ctrl.updateClassDefaultAmount)
router.put('/classes/:classId/initial-balance',  ctrl.updateInitialBalance)
router.delete('/classes/:classId',               ctrl.deleteClass)
router.post('/classes/:classId/students',        ctrl.addStudent)
router.get('/classes/:classId/students',         ctrl.getClassStudents)
router.delete('/students/:studentId',            ctrl.deleteStudent)
router.post('/payments/create-monthly',          ctrl.createMonthlyPayments)
router.get('/payments/class/:classId',           ctrl.getClassPayments)
router.get('/payments',                          ctrl.getMonthlyPayments)
router.put('/payments/:paymentId/status',        ctrl.updatePaymentStatus)
router.get('/reminder',                          ctrl.getMonthlyReminder)
router.post('/sms-reminder/send',                ctrl.sendSmsReminders)
router.get('/export/:classId',                   ctrl.exportPayments)
router.post('/expenses',                         ctrl.addExpense)
router.get('/expenses',                          ctrl.getExpenses)
router.delete('/expenses/:expenseId',            ctrl.deleteExpense)
router.get('/telegram/bot-link',                 tgCtrl.getBotLink)
router.get('/telegram/parents',                  tgCtrl.getParents)
router.get('/telegram/parents/class/:classId',   tgCtrl.getParentsByClass)
router.post('/telegram/send-reminders',          tgCtrl.sendRemindersNow)
router.post('/telegram/send-to-students',        tgCtrl.sendToStudents)

module.exports = router